[package]
name = "vft-common"
version.workspace = true
edition.workspace = true

[dependencies]
awesome-sails.workspace = true
awesome-sails-services = { workspace = true, features = [
    "vft-native-exchange",
] }
sails-rs.workspace = true
