[package]
name = "genesis-config"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
cli-utils.workspace = true
gear-rpc-client.workspace = true
hex.workspace = true
tokio.workspace = true
