[package]
name = "governance-tool"
version.workspace = true
edition.workspace = true

[dependencies]
alloy.workspace = true
clap.workspace = true
cli-utils.workspace = true
gprimitives = { workspace = true, features = ["serde"] }
hex = { workspace = true, features = ["std"] }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
